image: ubuntu
branches:
  only:
    - master
install:
  - npm install
build_script:
  - npm run build
on_success:
  - git config --global user.email "appveyor@example.com"	
  - git config --global user.name "AppVeyor"
  - npm run deploy
